
gems:
- jekyll-sitemap

# Site settings
title: Sample Site
permalink: pretty

default_lang: 'en'
languages: ['en']


# Build settings
exclude:
  - 'sitemap.json'
  
keep_files: ['assets']
rsync_copy: ['_assets']

#page_gen:
#  - data: 'arts'
#    template: 'destination-details'
#    dir: 'arts'
